import {Injectable} from '@angular/core';
import {LapinModel} from "../models/lapin.model";

@Injectable({
  providedIn: 'root'
})

export class LapinService {
  lapins: LapinModel[] = [
    {
      id: 1,
      nom: "Babouche",
      photo: "../../assets/images/lapins/babouche.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-03-18",
      couleur: "Noire et Blanche",
      caractere: "Calme et reservée. Elle aime les câlins. Mais ne venez surtout pas piquer sa gamelle elle y tient beaucoup",
    },
    {
      id: 2,
      nom: "Citrouille",
      photo: "../../assets/images/lapins/citrouille.jpg",
      sexe: "Mâle",
      dateNaissance: "2020-12-13",
      couleur: "Brun et Noir",
      caractere: "Energique il ne manque pas de courir partout ! Il va beaucoup vous amuser, surtout si vous avez un enfant qui aime courir !",
    },
    {
      id: 3,
      nom: "Oscar",
      photo: "../../assets/images/lapins/oscar.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-02-01",
      couleur: "Blanc",
      caractere: "Adore les câlins et surtout la sieste de l'après-midi. Vous pourrez passer des journées au coin du feu avec un livre et oscar qui vous câline.",
    },
    {
      id: 4,
      nom: "Snoopy",
      photo: "../../assets/images/lapins/snoopy.jpg",
      sexe: "Mâle",
      dateNaissance: "2021-10-01",
      couleur: "Brunc et Blanc",
      caractere: "Il paraît snob mais ce n'est qu'une façade ne vous inquiétez pas il est adorable !",
    },
    {
      id: 5,
      nom: "Zoreille",
      photo: "../../assets/images/lapins/zoreille.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-02-01",
      couleur: "Grise",
      caractere: "Elle est très timide alors faites doucement et donnez lui de l'amour !",
    },
    {
      id: 6,
      nom: "Rabbit",
      photo: "../../assets/images/lapins/rabbit.jpg",
      sexe: "Mâle",
      dateNaissance: "2018-01-01",
      couleur: "Blanc et Gris",
      caractere: "C'est un grand fou, si vous cherchez un compagnon énergique c'est lui tout craché !",
    },
    {
      id: 7,
      nom: "Grizzly",
      photo: "../../assets/images/lapins/grizzly.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-09-13",
      couleur: "Blanc, Gris et Brun",
      caractere: "Grizzly fait parti de la team des chenapans, il fait pleins de petites bêtises, mais avec sa bouille, on lui pardonne..",
    },
    {
      id: 8,
      nom: "Pâques",
      photo: "../../assets/images/lapins/pâques.jpg",
      sexe: "Femelle",
      dateNaissance: "2018-12-02",
      couleur: "Noire",
      caractere: "C'est le plus adorable des lapins, elle fait des câlins vraiment très souvent !",
    },
    {
      id: 9,
      nom: "Lily",
      photo: "../../assets/images/lapins/lily.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-08-01",
      couleur: "Brune et Noire",
      caractere: "Surtout pensez à la nourriture, c'est une petite gourmande !",
    },
    {
      id: 10,
      nom: "Frida",
      photo: "../../assets/images/lapins/frida.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-06-01",
      couleur: "Grise et Blanche",
      caractere: "Cela se voit à sa tête que c'est un lapin sage et calme, et je vous assure que c'est vrai !",
    },
    {
      id: 11,
      nom: "Nala",
      photo: "../../assets/images/lapins/nala.jpg",
      sexe: "Femelle",
      dateNaissance: "2021-01-01",
      couleur: "Brune et Blanche",
      caractere: "Cette petite chipie a gardé son âme d'enfance et cela ne la rend que plus mignonne.",
    },
    {
      id: 12,
      nom: "Godzilla",
      photo: "../../assets/images/lapins/godzilla.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-01-01 ",
      couleur: "Brune",
      caractere: "Comme son nom l'indique, c'est une petite brute mais elle a beaucoup d'amour à donner !",
    },
    {
      id: 13,
      nom: "Kiss",
      photo: "../../assets/images/lapins/kiss.jpg",
      sexe: "Femelle",
      dateNaissance: "2020-12-02",
      couleur: "Grise",
      caractere: "Même si ce n'est plus une enfant, donnez lui le plus de bisous possible, elle adore ça ! D'où le nom !",
    },
    {
      id: 14,
      nom: "Natsu",
      photo: "../../assets/images/lapins/natsu.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-01-01",
      couleur: "Brun et Blanc",
      caractere: "Ce petit chenapan adore Fairy Tail, c'est sans doute grâce à son nom, mais mettez lui un épisode et c'est le plus heureux.",
    },
    {
      id: 15,
      nom: "Dahlia",
      photo: "../../assets/images/lapins/dahlia.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-01-01",
      couleur: "Brune",
      caractere: "Dahlia est une adorable petite boule de poils, mais elle est aussi bien gourmande !",
    },
    {
      id: 16,
      nom: "Violette",
      photo: "../../assets/images/lapins/violette.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-09-29",
      couleur: "Grise et Blanche",
      caractere: "Violette adore se blottir dans vos bras dans n'importe quel situation !",
    },
    {
      id: 17,
      nom: "Cacahuète",
      photo: "../../assets/images/lapins/cacahuete.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-03-01",
      couleur: "Brun et Blanc",
      caractere: "Un grand chenapan qui est très ami avec tout  le monde, mais qui n'oublie jamais de venir chercher son câlin.",
    },
    {
      id: 18,
      nom: "Yuki",
      photo: "../../assets/images/lapins/yuki.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-01-01",
      couleur: "Noir",
      caractere: "Un grand amoureux du foin, il faut faire gaffe, il a tendance à en mettre partout, mais il est si mignon quand il en mange..",
    },
    {
      id: 19,
      nom: "Flinch",
      photo: "../../assets/images/lapins/flinch.jpg",
      sexe: "Femelle",
      dateNaissance: "2021-06-01",
      couleur: "Brune",
      caractere: "Calme et reservée, lorsqu'elle s'habitue à vous elle s'ouvre beaucoup et est vraiment adorable !",
    },
    {
      id: 20,
      nom: "Mimi",
      photo: "../../assets/images/lapins/mimi.jpg",
      sexe: "Femelle",
      dateNaissance: "2021-06-01",
      couleur: "Blanche",
      caractere: "Comme son nom l'indique, elle est toute mimi et adore regarder ses amis jouer pendant que vous la caressez.",
    },
    {
      id: 21,
      nom: "Brown",
      photo: "../../assets/images/lapins/brown.jpg",
      sexe: "Mâle",
      dateNaissance: "2019-02-21",
      couleur: "Brun",
      caractere: "Même s'il fait parti des plus vieux, il continue de draguer toutes les lapines autour de lui ce petit coquin.",
    },
    {
      id: 22,
      nom: "Oh-ho",
      photo: "../../assets/images/lapins/oh-ho.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-11-13",
      couleur: "Blanc",
      caractere: "Il est très explorateur et curieux et il n'aime pas être pris dans les bras mais n'hésite pas à nous monter dessus sur le canapé.",
    },
    {
      id: 23,
      nom: "Vanna ",
      photo: "../../assets/images/lapins/vanna.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-04-13",
      couleur: "Brune",
      caractere: "Elle est de petit gabarit, avec un petit caractère mais elle est très mignonne, et reste dans les bras pour faire des câlins !",
    },
    {
      id: 24,
      nom: "Titus",
      photo: "../../assets/images/lapins/titus.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-01-13",
      couleur: "Brun",
      caractere: "C'est un petit gourmand qui ne manque pas de caractère, il n’hésitera pas à taper de la patte si on ose le déranger, mais il adore les bisous et les câlins.",
    },
    {
      id: 25,
      nom: "Fuji",
      photo: "../../assets/images/lapins/fuji.jpg",
      sexe: "Femelle",
      dateNaissance: "2019-01-13",
      couleur: "Blanche, Brune et Noire",
      caractere: "Fuji est attachante, elle apprécie de se faire caresser. Elle est bien sûr gourmande et curieuse, une vraie boule d'amour !",
    },
    {
      id: 26,
      nom: "Toffee",
      photo: "../../assets/images/lapins/toffee.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-10-18",
      couleur: "Gris",
      caractere: "Toffee a beaucoup de moments où il est calme, et adore se faire câliner pendant ce temps. Toutefois, ça reste un jeune lapin avec beaucoup d'énergie !",
    },
    {
      id: 27,
      nom: "Twinkle",
      photo: "../../assets/images/lapins/twinkle.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-10-18",
      couleur: "Bleu merle",
      caractere: "Twinkle est le plus curieux de tous. Il adore explorer, fouiller mais surtout être en hauteur. Il accourt nous voir dès qu'on entre dans la pièce.",
    },
    {
      id: 28,
      nom: "Pralinou",
      photo: "../../assets/images/lapins/pralinou.jpg",
      sexe: "Mâle",
      dateNaissance: "2021-06-01",
      couleur: "Marron et blanc",
      caractere: "Une chose est sûre, il a beaucoup d'énergie et remplira votre foyer de bonheur.",
    },
    {
      id: 29,
      nom: "Ice-Tea",
      photo: "../../assets/images/lapins/ice-tea.jpg",
      sexe: "Mâle",
      dateNaissance: "2022-06-15",
      couleur: "Blanc et Noir",
      caractere: "Il est très mignon et aime intérargir avec l'humain ne mord pas et réclame des caresses. ",
    },
    {
      id: 30,
      nom: "Tartine",
      photo: "../../assets/images/lapins/tartine.jpg",
      sexe: "Femelle",
      dateNaissance: "2022-06-15",
      couleur: "Grise",
      caractere: "Tartine est encore un peu timide mais elle vient volontiers réclamer des friandise.",
    },
  ];

  getAllLapins(): LapinModel[] {
    return this.lapins;
  }

  rajouterLapin(formValue: { nom: string, photo: string, sexe: string, dateNaissance : string, couleur: string, caractere: string }) {
    const lapin: LapinModel = {
      ...formValue,
      id: this.lapins[this.lapins.length - 1].id + 1
    };
    this.lapins.push(lapin);
  }

  getId(id: number): LapinModel {
    const lapin = this.lapins.find(lapin => lapin.id == id);
    // @ts-ignore
    return lapin;
  }
}
