import {Injectable} from '@angular/core';
import {ObjetModel} from "../models/objet.model";

@Injectable({
  providedIn: 'root'
})

export class ObjetService {
  objets: ObjetModel[] = [
    {
      id: 1,
      nom: "Ballot de 10kg de foin de prairie",
      photo: "../../assets/images/objets/Foin-depoussiere-10-kg-2.jpg.webp",
      prix: "31,60",
      type: "nourriture",
    },
    {
      id: 2,
      nom: "Haltère gourmande",
      photo: "../../assets/images/objets/Alteres-Popcorn-2.png.webp",
      prix: "13,50",
      type: "nourriture",
    },
    {
      id: 3,
      nom: "Foin premium de montagne, sac 4kg",
      photo: "../../assets/images/objets/Foin-de-montagne-10-2.jpg.webp",
      prix: "18,90",
      type: "nourriture",
    },
    {
      id: 4,
      nom: "Sucette florale",
      photo: "../../assets/images/objets/glace-7.jpg.webp",
      prix: "6,90",
      type: "nourriture",
    },
    {
      id: 5,
      nom: "Feuilles de framboisier",
      photo: "../../assets/images/objets/feuilles-de-framboisier-2-1024x1024.jpg.webp",
      prix: "6,20",
      type: "nourriture",
    },
    {
      id: 6,
      nom: "Chips pommes séchées",
      photo: "../../assets/images/objets/chips-de-pomme-1-2-1024x1024.jpg.webp",
      prix: "5,90",
      type: "nourriture",
    },
    {
      id: 7,
      nom: "Râtelier à foin Romarin",
      photo: "../../assets/images/objets/ratelier-Romarin-3-1.png.webp",
      prix: "28,90",
      type: "habitat",
    },
    {
      id: 8,
      nom: "Le râtelier-litière medium pour lapin",
      photo: "../../assets/images/objets/ratelier-medium-turquoise-1024x1024.jpg.webp",
      prix: "82,00",
      type: "habitat",
    },
    {
      id: 9,
      nom: "Panier “Dream Away”",
      photo: "../../assets/images/objets/dream-away-1-1.jpg.webp",
      prix: "55,00",
      type: "habitat",
    },
    {
      id: 10,
      nom: "Sapin",
      photo: "../../assets/images/objets/Arbre-de-Noel-3.jpg.webp",
      prix: "19,20",
      type: "habitat",
    },
    {
      id: 11,
      nom: "Maison Pollux taille XXL",
      photo: "../../assets/images/objets/VIV0108-2-2.png.webp",
      prix: "64,90",
      type: "habitat",
    },
    {
      id: 12,
      nom: "Tunnel Ornikar",
      photo: "../../assets/images/objets/tunnel-ornikar-1-1024x1024.jpg.webp",
      prix: "28,90",
      type: "habitat",
    },
    {
      id: 13,
      nom: "La carotte en fibres végétales",
      photo: "../../assets/images/objets/Carotte-en-foin-2-1024x1024.jpg.webp",
      prix: "6,50",
      type: "jouet",
    },
    {
      id: 14,
      nom: "Jeu en bois le “Bac +10”",
      photo: "../../assets/images/objets/Jeu-bac-10-2.jpg.webp",
      prix: "18,90",
      type: "jouet",
    },
    {
      id: 15,
      nom: "L’arbre à légumes ou à branchages",
      photo: "../../assets/images/objets/Larbre-1-2-1024x1024.jpg.webp",
      prix: "14,90",
      type: "jouet",
    },
    {
      id: 16,
      nom: "Tunnel au foin 750g",
      photo: "../../assets/images/objets/tunnel-au-foin-2-1024x1024.jpg.webp",
      prix: "25,90",
      type: "jouet",
    },
    {
      id: 17,
      nom: "Trio de balles",
      photo: "../../assets/images/objets/trio-2-1024x1024.jpg.webp",
      prix: "8,50",
      type: "jouet",
    },
    {
      id: 18,
      nom: "Passerelle",
      photo: "../../assets/images/objets/VIV0382.jpg.webp",
      prix: "14,80",
      type: "jouet",
    },
    {
      id: 19,
      nom: "The big ball",
      photo: "../../assets/images/objets/The-big-ball-5-1024x1024.jpg.webp",
      prix: "13,60",
      type: "jouet",
    },
    {
      id: 20,
      nom: "Râtelier Déliss-Roll XXL",
      photo: "../../assets/images/objets/deliss-roll-a-suspendre-4.jpg.webp",
      prix: "13,15",
      type: "jouet",
    },
    {
      id: 21,
      nom: "Bascule Krokmou",
      photo: "../../assets/images/objets/Bascule-krokmou-1-2.png.webp",
      prix: "29,90",
      type: "jouet",
    },
    {
      id: 22,
      nom: "Attrap’friandises",
      photo: "../../assets/images/objets/Attrapdouceurs-3-1024x1024.jpg.webp",
      prix: "9,90",
      type: "jouet",
    },
    {
      id: 23,
      nom: "Tapis de fouille Marguerite",
      photo: "../../assets/images/objets/marguerite-3-3-1024x1024.jpg.webp",
      prix: "18,90",
      type: "jouet",
    },
    {
      id: 24,
      nom: "Blue Snack Roll pour lapin",
      photo: "../../assets/images/objets/snack-roll-3.jpg.webp",
      prix: "5,50",
      type: "jouet",
    },
    {
      id: 25,
      nom: "Le ratelier à foin roulant",
      photo: "../../assets/images/objets/le-ratelier-à-foin-roulant-5-1024x1024.jpg.webp",
      prix: "9,80",
      type: "jouet",
    },
    {
      id: 26,
      nom: "Pont flexible en rondins de bois XL",
      photo: "../../assets/images/objets/tunnel-en-rondins-de-bois-4.jpg.webp",
      prix: "18,90",
      type: "jouet",
    },
    {
      id: 27,
      nom: "Balle XL en bois de saule",
      photo: "../../assets/images/objets/VIV4383-1024x1024.jpg.webp",
      prix: "9,70",
      type: "jouet",
    },
    {
      id: 28,
      nom: "Foin BIO de Normandie sac jute,4 kg",
      photo: "../../assets/images/objets/foin-bio-2-1024x1024.jpg.webp",
      prix: "29,00",
      type: "nourriture",
    },
    {
      id: 29,
      nom: "Papaya Support Oxbow",
      photo: "../../assets/images/objets/Composition-Papaye-1024x1024.jpg.webp",
      prix: "15,20",
      type: "nourriture",
    },
    {
      id: 30,
      nom: "Betterave",
      photo: "../../assets/images/objets/Betterave-3-1024x1024.jpg.webp",
      prix: "5,50",
      type: "nourriture",
    },
    {
      id: 31,
      nom: "Echinacée",
      photo: "../../assets/images/objets/echinacea-1.jpg.webp",
      prix: "4,90",
      type: "nourriture",
    },
    {
      id: 32,
      nom: "Coeurs au foin, banane et pomme",
      photo: "../../assets/images/objets/coeurs-pomme-banane-oxbow-2-1024x1024.jpg.webp",
      prix: "7,50",
      type: "nourriture",
    },
    {
      id: 33,
      nom: "Chips pommes séchées",
      photo: "../../assets/images/objets/chips-de-pomme-1-2-1024x1024.jpg.webp",
      prix: "5,90",
      type: "nourriture",
    },
    {
      id: 34,
      nom: "Bleuet rouge",
      photo: "../../assets/images/objets/bleuet-rouge-1-1024x1024.jpg.webp",
      prix: "6,50",
      type: "nourriture",
    },
    {
      id: 35,
      nom: "Or à lapin",
      photo: "../../assets/images/objets/or-a-lapin-6-1024x1024.jpg.webp",
      prix: "14,50",
      type: "nourriture",
    },
    {
      id: 36,
      nom: "Petits coeurs au foin et aux fleurs",
      photo: "../../assets/images/objets/coeurs.webp",
      prix: "6,20",
      type: "nourriture",
    },
    {
      id: 37,
      nom: "La maison douillette",
      photo: "../../assets/images/objets/Maison-douillette-3-1024x1024.jpg.webp",
      prix: "46,00",
      type: "habitat",
    },
    {
      id: 38,
      nom: "Le tunnel douillet",
      photo: "../../assets/images/objets/Tunnel-2-1024x1024.jpg.webp",
      prix: "34,90",
      type: "habitat",
    },
    {
      id: 39,
      nom: "Le tapis en fibres naturelles",
      photo: "../../assets/images/objets/tapis-naturel.jpg.webp",
      prix: "6,60",
      type: "habitat",
    },
    {
      id: 40,
      nom: "La bunny TV",
      photo: "../../assets/images/objets/bunny-TV-1-2.jpg.webp",
      prix: "79,80",
      type: "habitat",
    },
    {
      id: 41,
      nom: "Maison Helheim",
      photo: "../../assets/images/objets/VIV0010.png.webp",
      prix: "39,90",
      type: "habitat",
    },
    {
      id: 42,
      nom: "Charrette à foin",
      photo: "../../assets/images/objets/Charette-a-foin-3-1.jpg.webp",
      prix: "36,00",
      type: "habitat",
    },
    {
      id: 43,
      nom: "Le cocon",
      photo: "../../assets/images/objets/Image-1-1-1024x1024.jpg.webp",
      prix: "43,00",
      type: "habitat",
    },
    {
      id: 44,
      nom: "Roll N Flop",
      photo: "../../assets/images/objets/Roll-N-Flop-5.jpg.webp",
      prix: "35,90",
      type: "habitat",
    },
    {
      id: 45,
      nom: "Toile hamac fausse fourrure XL",
      photo: "../../assets/images/objets/5-couleurs-hamac-1-1024x1024.jpg.webp",
      prix: "31,00",
      type: "habitat",
    },
    {
      id: 46,
      nom: "Secure Bunny, anti-stress",
      photo: "../../assets/images/objets/secure-bunny-4-1.jpg.webp",
      prix: "18,95",
      type: "accessoire",
    },
    {
      id: 47,
      nom: "Assiette en bois",
      photo: "../../assets/images/objets/assiette-1.jpg.webp",
      prix: "36,00",
      type: "accessoire",
    },
    {
      id: 48,
      nom: "Caisse de transport en plastique",
      photo: "../../assets/images/objets/caisse-de-transport-eco-4-1024x1024.jpg.webp",
      prix: "19,50",
      type: "accessoire",
    },
    {
      id: 49,
      nom: "Le gant magique",
      photo: "../../assets/images/objets/gant-4-1024x1024.jpg.webp",
      prix: "7,90",
      type: "accessoire",
    },
    {
      id: 50,
      nom: "Coupe-griffes pour lapins",
      photo: "../../assets/images/objets/coupe-ongle-1-2.jpg.webp",
      prix: "9,90",
      type: "accessoire",
    },
    {
      id: 51,
      nom: "Harnais pour grands lapins",
      photo: "../../assets/images/objets/harnais-4-1-1024x1024.jpg.webp",
      prix: "11,90",
      type: "accessoire",
    },
    {
      id: 52,
      nom: "Bac litière small",
      photo: "../../assets/images/objets/Litiere-small-pastel-10-1024x1024.jpg.webp",
      prix: "6,00",
      type: "accessoire",
    },
    {
      id: 53,
      nom: "Sac à foin nouvelle collection",
      photo: "../../assets/images/objets/VIV9233.jpg.webp",
      prix: "26,90",
      type: "accessoire",
    },
    {
      id: 54,
      nom: "Bac à litière taille medium",
      photo: "../../assets/images/objets/bac-bleu-3-1024x1024.jpg.webp",
      prix: "9,50",
      type: "accessoire",
    },
    {
      id: 55,
      nom: "La caisse de transport confort",
      photo: "../../assets/images/objets/Caisse-de-transport-luxe-3-1024x1024.jpg.webp",
      prix: "65,20",
      type: "accessoire",
    },
    {
      id: 56,
      nom: "Harnais pour lapins nains",
      photo: "../../assets/images/objets/harnais-1-1024x1024.jpg.webp",
      prix: "9,90",
      type: "accessoire",
    },
    {
      id: 57,
      nom: "Module écuelles taille small",
      photo: "../../assets/images/objets/module-ecuelles-medium-6-1024x1024.jpg.webp",
      prix: "25,20",
      type: "accessoire",
    },
    {
      id: 58,
      nom: "Ecuelle Welcome",
      photo: "../../assets/images/objets/ecuelle-6-1024x1024.jpg.webp",
      prix: "8,50",
      type: "accessoire",
    },
    {
      id: 59,
      nom: "Râtelier-litière avec écuelles",
      photo: "../../assets/images/objets/Ratelier-litiere-mangeoires-4-1024x1024.jpg.webp",
      prix: "99,00",
      type: "accessoire",
    },
    {
      id: 60,
      nom: "Tapis hygiénique",
      photo: "../../assets/images/objets/tapis-hygieniques-2-1024x1024.jpg.webp",
      prix: "18,90",
      type: "accessoire",
    },
  ];

  getAllObjets(): ObjetModel[] {
    return this.objets;
  }
}

